### ISSUE TITLE
iOS beta 版配布時のアイコン加工で version を表示しようとすると CI が頻繁にこける

### ISSUE THREAD

**Issue by starhoshi** [classi/fastlane-example#6]
iOS の beta 版配布で、 badge を利用しアプリアイコンを加工し、 version 情報の表記と beta バッジを表示している。
しかし、この処理のせいで CI が頻繁にこけてしまっている。

[Shield\.io \.png occasionally isnt created correctly · Issue \#49 · HazAT/badge](https://github.com/HazAT/badge/issues/49)

上記 issue に書かれているが、 `librsvg` を導入すると安定するっぽい。
しかし、以前 `brew install librsvg` したら数分かかった記憶がある。CircleCI は時間課金なので、数分レベルでかかってしまうのは苦しい。

## 対策

version 情報を表示する処理を削除することにした。 
version 情報の表示を無くしても `beta` というバッジは表示されるので beta 版であるという主張はできる。
version は残念ながら表示されなくなるが、しょうがない。

## エラーログ

```
INFO [2017-06-26 10:43:01.53]: -------------------
INFO [2017-06-26 10:43:01.53]: --- Step: badge ---
INFO [2017-06-26 10:43:01.53]: -------------------
INFO [2017-06-26 10:43:01.65]: gem 'badge' is already installed
WARN [2017-06-26 10:43:01.68]: Install RSVG to get better results for shields ontop of your icon
WARN [2017-06-26 10:43:01.68]: 
WARN [2017-06-26 10:43:01.68]: Install it using (RSVG):
INFO [2017-06-26 10:43:01.68]: $ brew install librsvg
WARN [2017-06-26 10:43:01.68]: 
DEBUG [2017-06-26 10:43:01.77]: Verbose active... VERSION: 0.8.4
DEBUG [2017-06-26 10:43:01.77]: Parameters: [true, nil, nil, "1.0.7-14984413-blue", nil, nil, nil, nil, nil, nil]
INFO [2017-06-26 10:43:01.77]: Start adding badges...
DEBUG [2017-06-26 10:43:01.77]: Trying to load image from shield.io. Timeout: 10s
DEBUG [2017-06-26 10:43:01.77]: URL: https://img.shields.io/badge/1.0.7-14984413-blue.png
INFO [2017-06-26 10:43:02.29]: './hoge/Assets.xcassets/AppIcon.appiconset/appicon-60.png'
DEBUG [2017-06-26 10:43:02.29]: Adding badge image ontop of icon
INFO [2017-06-26 10:43:02.33]: './hoge/Assets.xcassets/AppIcon.appiconset/appicon-60.png'
DEBUG [2017-06-26 10:43:02.33]: Adding shield.io image ontop of icon
DEBUG [2017-06-26 10:43:02.34]: /Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:204:in `rescue in validate!'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:202:in `validate!'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:113:in `block in create'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `tap'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `create'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:34:in `read'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:90:in `block in open'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:89:in `open'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/badge-0.8.4/lib/badge/runner.rb:106:in `add_shield'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/badge-0.8.4/lib/badge/runner.rb:66:in `block in run'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/badge-0.8.4/lib/badge/runner.rb:55:in `each'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/badge-0.8.4/lib/badge/runner.rb:55:in `run'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/actions/badge.rb:20:in `run'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
../../../../var/folders/jm/fw86rxds0xn69sk40d18y69m0000gp/T/fl_clone20170626-4575-1ejyzw9/fastlane-example/iOS/fastlane/Fastfile:57:in `block (2 levels) in parsing_binding'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane.rb:33:in `call'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.37.0/bin/fastlane:20:in `<top (required)>'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
/Users/distiller/hoge_app/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/opt/rubies/ruby-2.3.1/bin/bundle:23:in `load'
/opt/rubies/ruby-2.3.1/bin/bundle:23:in `<main>'
INFO [2017-06-26 10:43:03.01]: Sending crash report...
INFO [2017-06-26 10:43:03.01]: The stacktrace is sanitized so no personal information is sent.
INFO [2017-06-26 10:43:03.01]: To see what we are sending, look here: /Users/distiller/.fastlane/latest_crash.json
INFO [2017-06-26 10:43:03.01]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
INFO [2017-06-26 10:43:03.01]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
```

**Comment by starhoshi** [comment]
対応コミット

https://github.com/classi/fastlane-example/commit/50778012f93839de1840f33276329b1f6b6d7e9a
